### ISSUE TITLE
Path error

### ISSUE THREAD

**Issue by jianwamazon** [aws-samples/amazon-ecs-mythicalmysfits-workshop#1]
In the HINT section of below instruction: 
https://github.com/aws-samples/amazon-ecs-mythicalmysfits-workshop/tree/master/workshop-2/Lab-3#create-new-buildspec-and-merge-feature-branch

`$ cp ~/environment/amazon-ecs-mythicalmysfits-workshop-staging/workshop-2/Lab-3/hints/buildspec_prod.yml ~/environment/REPLACEME_REPO_NAME/buildspec_prod.yml`

folder **amazon-ecs-mythicalmysfits-workshop-staging** does not exist, it should be **amazon-ecs-mythicalmysfits-workshop**

**Comment by hub714** [comment]
https://github.com/aws-samples/amazon-ecs-mythicalmysfits-workshop/commit/804d71ae7f0621cc03f22594a4b597fffe5019b8
