### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by jianwamazon** [aws-samples/amazon-ecs-mythicalmysfits-workshop#2]
The instruction link below mentioned "Find the app/monolith-service/service/mythicalMysfitsService.py source file, and **uncomment the following section**"

https://github.com/aws-samples/aws-modern-application-workshop/tree/fargate/workshop-1#instructions-2

Feedback: 
1. Provide full path
2. Remind user to remove extra whitespace when removing "#" to avoid indentation error.

**Comment by hub714** [comment]
Not this repo. closing.
