### ISSUE TITLE
Docker run detached

### ISSUE THREAD

**Issue by justinhiggins** [aws-samples/amazon-ecs-mythicalmysfits-workshop#4]
Add the "-d" flag to the "docker run" command in Lab 1 to run the container in the background and return to the command line.  This negates the need to be stuck on the waiting for (ctrl-c). 

example: 
docker run -d -p 8000:80 -e AWS_DEFAULT_REGION=eu-west-1 -e DDB_TABLE_NAME=Table-mythical-mysfits-fargate monolith-service

**Comment by hub714** [comment]
We actually did this so it would be easier to just kill the container instead of finding the container and killing it.
