### ISSUE TITLE
Cloud Formation Outputs - Script run error

### ISSUE THREAD

**Issue by anmonu** [aws-samples/amazon-ecs-mythicalmysfits-workshop#8]
After running script/setup

Installing dependencies...
Loaded plugins: priorities, update-motd, upgrade-helper
amzn-main                                                                                                                                                                    | 2.1 kB  00:00:00     
amzn-updates                                                                                                                                                                 | 2.5 kB  00:00:00     
1065 packages excluded due to repository priority protections
Resolving Dependencies
--> Running transaction check
---> Package jq.x86_64 0:1.5-1.2.amzn1 will be installed
--> Processing Dependency: jq-libs(x86-64) = 1.5-1.2.amzn1 for package: jq-1.5-1.2.amzn1.x86_64
--> Processing Dependency: oniguruma for package: jq-1.5-1.2.amzn1.x86_64
--> Processing Dependency: libonig.so.2()(64bit) for package: jq-1.5-1.2.amzn1.x86_64
--> Processing Dependency: libjq.so.1()(64bit) for package: jq-1.5-1.2.amzn1.x86_64
--> Running transaction check
---> Package jq-libs.x86_64 0:1.5-1.2.amzn1 will be installed
---> Package oniguruma.x86_64 0:5.9.1-3.1.2.amzn1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

====================================================================================================================================================================================================
 Package                                       Arch                                       Version                                               Repository                                     Size
====================================================================================================================================================================================================
Installing:
 jq                                            x86_64                                     1.5-1.2.amzn1                                         amzn-main                                      44 k
Installing for dependencies:
 jq-libs                                       x86_64                                     1.5-1.2.amzn1                                         amzn-main                                     121 k
 oniguruma                                     x86_64                                     5.9.1-3.1.2.amzn1                                     amzn-main                                     149 k

Transaction Summary
====================================================================================================================================================================================================
Install  1 Package (+2 Dependent packages)

Total download size: 314 k
Installed size: 885 k
Downloading packages:
(1/3): jq-1.5-1.2.amzn1.x86_64.rpm                                                                                                                                           |  44 kB  00:00:00     
(2/3): jq-libs-1.5-1.2.amzn1.x86_64.rpm                                                                                                                                      | 121 kB  00:00:01     
(3/3): oniguruma-5.9.1-3.1.2.amzn1.x86_64.rpm                                                                                                                                | 149 kB  00:00:01     
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                               202 kB/s | 314 kB  00:00:01     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : oniguruma-5.9.1-3.1.2.amzn1.x86_64                                                                                                                                               1/3 
  Installing : jq-libs-1.5-1.2.amzn1.x86_64                                                                                                                                                     2/3 
  Installing : jq-1.5-1.2.amzn1.x86_64                                                                                                                                                          3/3 
  Verifying  : oniguruma-5.9.1-3.1.2.amzn1.x86_64                                                                                                                                               1/3 
  Verifying  : jq-1.5-1.2.amzn1.x86_64                                                                                                                                                          2/3 
  Verifying  : jq-libs-1.5-1.2.amzn1.x86_64                                                                                                                                                     3/3 

Installed:
  jq.x86_64 0:1.5-1.2.amzn1                                                                                                                                                                         

Dependency Installed:
  jq-libs.x86_64 0:1.5-1.2.amzn1                                                                oniguruma.x86_64 0:5.9.1-3.1.2.amzn1                                                               

Complete!
**Fetching CloudFormation outputs...
jq: error (at <stdin>:31): Cannot iterate over null (null)**
![Screenshot 2019-08-05 at 3 14 13 PM](https://user-images.githubusercontent.com/29253037/62445832-d13ca980-b793-11e9-96e0-d934bf560dfd.png)

**Comment by hub714** [comment]
Your stack never finished creating and it looks like you may have disabled rollback on failure, I think.

Since the stack didn't complete successfully, the script couldn't pull outputs. This is expected.
